# Generated by Django 5.2.1 on 2025-06-25 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('school', 'School Project'), ('side', 'Side Project'), ('professional', 'Professional Project')], max_length=20, verbose_name='Project Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('technologies', models.CharField(max_length=255, verbose_name='Technologies')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='GitHub Link')),
                ('demo_link', models.URLField(blank=True, null=True, verbose_name='Demo Link')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='School Name')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/projects/images/')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='SchoolProject',
        ),
    ]
