# Generated by Django 5.2.1 on 2025-06-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education_current_education_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='current',
        ),
        migrations.RemoveField(
            model_name='education',
            name='location',
        ),
    ]
